# Generated by Django 2.1.2 on 2018-10-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=True, editable=False, verbose_name='is_archived')),
                ('street_1', models.CharField(max_length=255, verbose_name='Address line 1')),
                ('street_2', models.CharField(blank=True, max_length=255, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Zip code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary address')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
