# Generated by Django 2.1.2 on 2018-10-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('addresses', '0002_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.UserProfile', verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='is_archived',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_archived'),
        ),
    ]
