# Generated by Django 2.1.2 on 2018-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20181013_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('heads', models.ManyToManyField(blank=True, related_name='managed_groups', to='users.UserProfile', verbose_name='Heads')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='users.UserProfile', verbose_name='Members')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
